### ISSUE TITLE
Attempting to use tool for republish of a particular content type

### ISSUE THREAD

**Issue by RickKrause** [amplience/dc-cli#117]
Attempting to perform a republish for a given content type (or group of content types) for the purposes of triggering webhook background processing.  The only way commands i can see to accomplish is an export and then import.  But when i attempt the import with --republish, it fails due to delivery key.  If i exclude keys, then a new content item is created, which is not the desired behavior.  

Is this the correct process for accomplishing this task, or is there other method?   May be a feature request.

**Comment by RickKrause** [comment]
Log Info:

// dc-cli 0.12.0 - C:\Users\rkrause\.amplience\logs\item-import-1636739832950.log
// Existing mapping loaded from 'C:\Users\rkrause\.amplience\imports\hub-5dc5e1b24cedfd0001795f18.json', changes will be saved back to it.
// Scanning structure and content in 'exportImportSameItemTest\Content' for repository 'Content'...
// Found existing subfolder in Content: 'Recipes'.
// Scanning structure and content in 'exportImportSameItemTest\Slots' for repository 'Slots'...
// Done. Validating content...
// 1 of the items being imported already exist in the mapping. Would you like to update these content items instead of skipping them? (y/n) y
// Found 1 dependancy levels in 1 items, 0 referencing a circular dependancy.
// Importing 1 content items...
ERROR 
// ERROR: Failed creating test-content-item:
// Error: Request failed with status code 409: {"errors":[{"level":"ERROR","code":"CONTENT_ITEM_DELIVERY_KEY_DUPLICATE","message":"Required delivery key already exists on this hub","property":"body._meta.deliveryKey","entity":"ContentItem","invalidValue":"recipes/test-content-item"}]}
// Importing content item failed, aborting. Error: Error: Request failed with status code 409: {"errors":[{"level":"ERROR","code":"CONTENT_ITEM_DELIVERY_KEY_DUPLICATE","message":"Required delivery key already exists on this hub","property":"body._meta.deliveryKey","entity":"ContentItem","invalidValue":"recipes/test-content-item"}]}
FAILURE

**Comment by RickKrause** [comment]
never mind, i used exclude keys and i think it provides functionality we're looking for and doesn't create a duplicate

**Comment by RickKrause** [comment]
Also, since the force is supposed to overwrite content, i would expect that  executing an export and then immediate import with --force, would have no affect on items.  I get duplicate delivery key error, and am unable to use.

**Comment by mdinning-amp** [comment]
Hi Rick

This sounds like the content item you're trying to import either doesn't exist in the mapping file, or exists with a different mapping.

The CLI relies on a mapping file (provided with the `--mapFile` argument, or automatically created/referenced if omitted) to match the exported content item in your filesystem to the intended target item in your hub. If importing without the mapFile argument and without a baseRepo/baseFolder argument, you should be able to find the mapping file in `<USERDIR>/.amplience/imports/hub-<TARGET-HUB-ID>.json`, and its contents will look something like this:

```
{
    "contentItems": [
        [
            "11111111-1111-1111-1111-111111111111",
            "22222222-2222-2222-2222-222222222222"
        ]
    ]
}
```

The first ID in each array is the source item's ID (contained in the export on your filesystem), and the second is the target ID in the destination hub.

If there is no mapping for the item you are importing, then it will try and create this as new. Similarly, if there _is_ a mapping but the target ID is different to the intended target, then the CLI will attempt to update this different content item instead. Whilst these scenarios would usually duplicate your content, this is compounded by delivery keys being unique to your hub. As this is trying to create/update a content item with a delivery key which already exists on the hub, this will be resulting in the error you are seeing.

We're due to release some documentation shortly which will better clarify the mapping file & its usage, but in the meantime I'd recommend checking your mapping to ensure that a mapping exists, and the target ID is correct. Please let us know if you still encounter issues after checking this, however.
